version: 2
jobs:
    build:
        docker:
            - image: docker
        steps:
            - checkout
            - run:
                name: Login
                command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
            - run:
                name: Build image
                command: docker build . -t olivejp/android-deploy:1.0.4
workflows:
    version: 2
    build_image:
        jobs:
            - build:
                  context: docker-android-deploy
