version: 2
jobs:
    build:
        docker:
            - image: docker
        steps:
            - checkout
            - run:
                name: Launc daemon docker
                command: |
                    docker run --privileged --name some-docker -d \
                    --network some-network --network-alias docker \
                    -e DOCKER_TLS_CERTDIR=/certs \
                    -v some-docker-certs-ca:/certs/ca \
                    -v some-docker-certs-client:/certs/client \
                    docker:dind
            - run:
                name: Login
                command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_HUB_PASSWORD}
            - run:
                name: Build image
                command: docker build . -t olivejp/android-deploy:1.0.4
workflows:
    version: 2
    build_image:
        jobs:
            - build:
                  context: docker-android-deploy
