version: 2
jobs:
    build:
        docker:
            - image: docker
        steps:
            - checkout
            - run:
                name: Login
                command: yes $DOCKER_PASSWORD | docker login --username=$DOCKER_USERNAME --email=$DOCKER_EMAIL
            - run:
                name: Build image
                command: docker build . -t olivejp/android-deploy:1.0.4
workflows:
    version: 2
    build_image:
        jobs:
            - build:
                  context: docker-android-deploy
